### ISSUE TITLE
Are there any plans on making this plugin available via the official Jenkins plugin page?

### ISSUE THREAD

**Issue by perostman** [thycotic/tss-jenkins-plugin#1]

**Comment by breimers** [comment]
Second this.

**Comment by EndlessTrax** [comment]
We have plans, and I've started the ball rolling on this. I will notify when available.

**Comment by EndlessTrax** [comment]
@breimers @perostman The Jenkins hosting issue seems to be stalled. I found out that the code reviews are done by volunteers. So we just have to wait. Maybe commenting on the issue to tell them you're waiting on this might help this get prioritized a little quicker?

https://issues.jenkins.io/browse/HOSTING-1104

**Comment by EndlessTrax** [comment]
This plugin is now available on the Jenkins official plugin page. 

https://plugins.jenkins.io/thycotic-secret-server/
