### ISSUE TITLE
Pipeline Support

### ISSUE THREAD

**Issue by usaecsw1** [thycotic/tss-jenkins-plugin#2]
It would be super useful if the plugin could be called from declarative / scripted pipelines.

**Comment by EndlessTrax** [comment]
We are planning to add pipeline support to the next release of the TSS Jenkins plugin. Thank you for your feedback. 

However, this plugin is now on the official Jenkins Repo and this fork is no longer the canonical and maintained. Please visit [https://github.com/jenkinsci/thycotic-secret-server-plugin](https://github.com/jenkinsci/thycotic-secret-server-plugin) for the latest version of this plugin. Future issues can be filed via the Jenkins Jira.
